#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --type=bool hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	# Note that the use of brackets around a tr range is ok here, (it's
	# even required, for portability to Solaris 10's /usr/bin/tr), since
	# the square bracket bytes happen to fall in the designated range.
	test $(git diff --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
	cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

If you know what you are doing you can disable this check using:

  git config hooks.allownonascii true
EOF
	exit 1
fi

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --

# Check if pre-commit is up-to-date.
#
# PRECOMMIT_MASTER_FILE='./script/pre-commit'
# if [ -e $PRECOMMIT_MASTER_FILE ]; then
#   diff -s $PRECOMMIT_MASTER_FILE ./.git/hooks/pre-commit > /dev/null 2>&1
#   if [ $? -ne 0 ]; then
#     cp $PRECOMMIT_MASTER_FILE ./.git/hooks/pre-commit
#     echo "updated pre-commit."
#     echo "pre-commit was not latest. Please run again." 1>&2
#     exit 1
#   fi
# else
#   echo "$PRECOMMIT_MASTER_FILE doesn't exist."
# fi

# Disallow commit on master and develop branch
#
# BRANCH_NAME=`git symbolic-ref HEAD | sed -e 's:^refs/heads/::'`
# if test $BRANCH_NAME = master -o $BRANCH_NAME = develop; then
#   echo "We cannot commit on ${BRANCH_NAME} branch."
#   exit 1
# fi

# Format C# scripts by Reshaper
cleanupcode.sh --include="Assets/Scripts/**/*" --profile="Reformat" UnityTemplate.sln

# Format C# scripts by dotnet-format. editorconfig
dotnet-format UnityTemplate.sln --include "Assets/Scripts/**/*.cs"
